name: Build Windows Binary

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build in scip-rust subdirectory
        run: cargo build --release
        working-directory: ./scip-rust

      - name: Compress .exe file
        run: Compress-Archive -Path target/release/scip-rust.exe -DestinationPath scip-rust-windows.zip
        working-directory: ./scip-rust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scip-rust-windows
          path: scip-rust/scip-rust-windows.zip
