name: Build Windows Binary

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build in subdirectory
        run: |
          cd scip-rust
          cargo build --release

      - name: Compress binary
        run: |
          Compress-Archive -Path scip-rust\target\release\scip-rust.exe -DestinationPath scip-rust-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scip-rust-windows
          path: scip-rust-windows.zip
